Representing DNA for Machine Learning Algorithms: A Primer on One-Hot, Binary, and Integer Encodings


This paper presents study of three popular methods for encoding DNA sequences: one-hot encoding, binary encoding, and integer encoding. DNA sequence encoding is an essential step in various bioinformatics and computational biology applications, enabling efficient representation and analysis of genetic data. Each encoding technique transforms the nucleotide-based DNA sequence into a numeric or binary representation, allowing for further computational processing and analysis.



--------------------------------------------------------------------------------------------------------------------------------

The provided Python code demonstrates three different methods for encoding DNA sequences: one-hot encoding, binary encoding, and integer encoding.

1. One-hot encoding:

In one-hot encoding, each nucleotide is represented as a binary vector with all elements set to 0 except for the index corresponding to the nucleotide, which is set to 1. The one-hot encoding is stored in a 2D NumPy array where each row corresponds to the one-hot encoded representation of the DNA sequence.

In [9]:
import numpy as np

# Sample DNA sequence
dna = 'ATGCCTAGTTACG' 

# Define nucleotides to encode
nucleotides = 'ATGC'

# Create a mapping from nucleotides to indices
encoding = {nucleotide: i for i, nucleotide in enumerate(nucleotides)}

# Initialize one-hot encoded array 
one_hot_encoded = np.zeros((len(dna), len(nucleotides)))

# One-hot encode the sequence
for i, nucleotide in enumerate(dna):
    one_hot_encoded[i, encoding[nucleotide]] = 1
        
print(one_hot_encoded)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


---------------------------------------------------------------------------------------------------------------------------------

2. Binary encoding:
    
Two bits to represent each nucleotide, which is the actual principle behind Binary Encoding in the context you're working with (DNA sequences). Each nucleotide is encoded into a binary pair, reducing the representation size compared to One-hot Encoding.

In [2]:
import numpy as np

dna = 'ATGCCTAGTTACG'

# Define binary mapping for each nucleotide
# Note: The representation here can vary based on convention; this is just one example.
binary_map = {'A': [0, 0],  # Represented as 00 in binary
              'T': [0, 1],  # Represented as 01 in binary
              'G': [1, 0],  # Represented as 10 in binary
              'C': [1, 1]}  # Represented as 11 in binary

# Perform binary encoding
binary_encoded = np.array([binary_map[nucleotide] for nucleotide in dna])

print('\nBinary encoded:\n', binary_encoded)



Binary encoded:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 0]]


---------------------------------------------------------------------------------------------------------------------------------

3. Integer encoding:

In integer encoding, each nucleotide is represented as an integer value based on a mapping defined for each nucleotide. The integer encoding is stored in a 1D NumPy array.

In [7]:
import numpy as np

dna = 'ATGCCTAGTTACG'

# Define integer mapping for each nucleotide
int_map = {'A': 0, 'T': 1, 'G': 2, 'C': 3}

# Perform integer encoding
int_encoded = [int_map[nucleotide] for nucleotide in dna]

print('\nInteger encoded:\n', int_encoded)



Integer encoded:
 [0, 1, 2, 3, 3, 1, 0, 2, 1, 1, 0, 3, 2]


--------------------------------------------------------------------------------------------------------------------------------

Each encoding method provides a different representation of the input DNA sequence, with its specific advantages and use cases in various applications.